version: '3.8'

services:
  fastapi1:
    build: .
    container_name: fastapi1
    environment:
      - TZ=Asia/Kolkata
    restart: always
    expose:
      - "8000"
    networks:
      - mynetwork

  fastapi2:
    build: .
    container_name: fastapi2
    environment:
      - TZ=Asia/Kolkata
    restart: always
    expose:
      - "8000"
    networks:
      - mynetwork

  fastapi3:
    build: .
    container_name: fastapi3
    environment:
      - TZ=Asia/Kolkata
    restart: always
    expose:
      - "8000"
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    container_name: nginx_lb
    environment:
      - TZ=Asia/Kolkata
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - fastapi1
      - fastapi2
      - fastapi3
    networks:
      - mynetwork

networks:
  mynetwork:
